name: products_app
description: "App for products view."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.4
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  intl: ^0.19.0
  
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
